server:
  port: 18000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logic_demo?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12#$qwER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
data-model:
  config-dir: ../data-model-configs
logging:
  level:
    debug: debug
swagger:
  enabled: true
