spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/datamodel?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://192.168.154.154:3306/xuanwu?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
data-model:
  config-dir: ../data-model-configs
  swagger:
    enabled: true
logging:
  level:
    debug: debug

